language: php
php:
  - '7.1'

branches:
  - only:
    - master
    - develop

addons:
  hosts:
    - elewant.loc

cache:
  directories:
    - vendor

install:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - mysql -e "create database elewant;"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'elewant'@'localhost'"
  - composer install

before_script:
  - echo 'date.timezone = "Europe/Amsterdam"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini

script:
  - bin/run_tests

notifications:
  email:
    on_success: change
