---

- name: Provision globally
  hosts: all
  become: yes
  remote_user: "{{ ssh_provision_user }}"
  gather_facts: yes

  pre_tasks:
    - name: Ensure the PHP FPM chdir / Nginx www dir exists
      file:
        path: "{{ php7_fpm_pool_chdir }}"
        owner: "{{ php7_fpm_pool_user }}"
        group: "{{ php7_fpm_pool_group }}"
        mode: 0755
        state: directory

  roles:
    - f500.debian
    - install_apt_packages
    - f500.locale
    - f500.ntp
    - f500.ufw
    - f500.supervisord
    - f500.bash
    - f500.bashrc
    - f500.vim

    - HanXHX.mysql
    - f500.php7
    - f500.php_composer
    - f500.nginx
    - f500.nodejs

  tasks:
    - name: Create the logs folder
      file: path=/home/logs state=directory

    - name: Add write privileges for the web user
      acl: name=/home/logs entity={{ nginx_user }} etype=user permissions=rw default=yes state=present

  post_tasks:
    - name: Install apt packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - acl
        - git

    - name: Install npm packages
      npm:
        name: "{{ item }}"
        global: yes
        state: present
      with_items:
        - grunt-cli

    - name: Install grunt
      npm: name=grunt-cli state=present global=yes

- name: Provision production
  hosts: production
  become: yes
  remote_user: "{{ ssh_provision_user }}"
  gather_facts: yes

  roles:
    - geerlingguy.certbot
    - { role: deployment_user,
        deployment_user: '{{ elewant_deploy_user_username }}',
        deployment_user_password: "{{ elewant_deploy_user_password }}",
        deployment_user_public_key: "{{ elewant_deploy_user_public_key }}",
        deployment_user_private_key: "{{ elewant_deploy_user_private_key }}"
      }

  tasks:
    - name: Add github.com to known_hosts file
      lineinfile: dest=/etc/ssh/ssh_known_hosts line="{{ lookup('pipe', 'ssh-keyscan github.com') }}" state=present  create=yes mode=0644

    - name: Remove cron for renew certificates (cron is created in certbot role)
      cron: name="certbot renew certificates" minute=0 hour=2,6 job="service nginx stop && certbot renew && service nginx start" state=absent

    - name: Restart nginx
      service:
        name: nginx
        state: restarted

    - name: Check for absent certificates
      stat:
        path: /etc/letsencrypt/live/{{ item.domains | first }}/cert.pem
      with_items: "{{ certbot_certs }}"
      register: webserver_letsencrypt

    - name: Create certificates
      shell: "{{ certbot_create_command }}"
      with_items: "{{ webserver_letsencrypt.results }}"
      when: not item.stat.exists

    - name: Copy supervisord configuration
      template:
        src: supervisord/elewant.herd_projection.conf.j2
        dest: /etc/supervisor/conf.d/elewant.conf
      notify: Reload supervisord configuration

- name: Provision develop environment
  hosts: develop
  become: no
  gather_facts: no

  tasks:
    - name: cd into /vagrant when logging in
      lineinfile:
        dest: /home/vagrant/.profile
        line: cd /vagrant
        insertafter: EOF

    - name: Add database hostname to hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ mariadb_bind_address }}  database_test"
        insertafter: EOF
      become: yes

    - name: Add the phpd alias for easy debugging from cli
      lineinfile:
        dest: /home/vagrant/.profile
        line: "alias phpd=\"php -dxdebug.remote_autostart=On\""
        insertafter: EOF

    - name: Copy parameters.yml
      template:
        src: "{{ playbook_dir }}/../deploy/templates/.env.j2"
        dest: "{{ elewant_application_root }}/.env"

    - name: Install composer packages
      command: composer install --quiet --no-ansi --no-interaction
      args:
        chdir: "{{ elewant_application_root }}"

    - name: Run migrations
      command: bin/console doctrine:migrations:migrate --no-interaction
      args:
        chdir: "{{ elewant_application_root }}"

    - name: Run Stream creation console command
      command: bin/console event-store:event-stream:create --no-interaction
      args:
        chdir: "{{ elewant_application_root }}"

    - name: Install npm packages
      npm:
        path: "{{ elewant_application_root }}"

    - name: Build assets
      command: grunt
      args:
        chdir: "{{ elewant_application_root }}"

    - name: Copy supervisord configuration
      become: yes
      template:
        src: supervisord/vagrant.herd_projection.conf.j2
        dest: /etc/supervisor/conf.d/elewant.conf

    - name: Restart Supervisord
      become: yes
      command: supervisorctl reread && supervisorctl update && supervisorctl reload
