---
galaxy_info:
  author: "Jasper N. Brouwer, Ramon de la Fuente"
  description: Install ntp service ans set default ntp servers
  company: Future500
  license: LGPL-3.0
  min_ansible_version: 1.4
  platforms:
  - name: Debian
    versions:
      - wheezy
      - jessie
      - stretch
      - buster
  categories:
    - system
dependencies: []
