---

galaxy_info:
  author: "Jasper N. Brouwer, Ramon de la Fuente"
  description: Install PHP version 7.X from deb.sury.org
  company: Future500
  license: LGPL-3.0
  min_ansible_version: 2.0
  platforms:
  - name: Debian
    versions:
      - jessie
      - wheezy
      - stretch
      - buster
  galaxy_tags:
    - web
