---

- name: Check if Composer is installed
  stat:
    path: "{{ php_composer_install_path }}"
  register: php_composer_binary

- name: Install packages needed to install Composer
  apt:
    name: wget
    state: present
  when: not php_composer_binary.stat.exists

- name: Create the install script
  copy:
    src: composer-install.sh
    dest: /tmp/composer-install.sh
    mode: 0755
  when: not php_composer_binary.stat.exists

- name: Install Composer
  command: ./composer-install.sh
  args:
    chdir: /tmp
  when: not php_composer_binary.stat.exists

- name: Remove the install script
  file:
    path: /tmp/composer-install.sh
    state: absent
  when: not php_composer_binary.stat.exists

- name: Move Composer to the install path
  command: mv /tmp/composer.phar "{{ php_composer_install_path }}"
  when: not php_composer_binary.stat.exists

- name: Enable the wrapper
  template:
    src: composer.j2
    dest: "{{ php_composer_wrapper_path }}"
    mode: 0755
  when: php_composer_wrapper_enabled | bool
