---
galaxy_info:
  author: "Jasper N. Brouwer, Ramon de la Fuente"
  description: "Install UWF (Uncomplicated Firewall)"
  company: Future500
  license: LGPL-3.0
  min_ansible_version: 1.6
  platforms:
  - name: Debian
    versions:
      - wheezy
      - jessie
      - stretch
      - buster
  galaxy_tags:
    - system
    - security
