prooph_event_store:
  stores:
    herd_store:
      adapter: 'prooph_event_store.doctrine_adapter.herd_store'
      repositories:
        herd_collection:
          repository_class: 'Elewant\Herding\Infrastructure\Repository\EventStoreHerdCollection'
          aggregate_type: 'Elewant\Herding\Model\Herd'
          aggregate_translator: 'prooph_event_sourcing.aggregate_translator'

services:
  prooph_event_store.doctrine_adapter.herd_store:
    class: Prooph\EventStore\Adapter\Doctrine\DoctrineEventStoreAdapter
    arguments: ['@database_connection', '@prooph_event_store.message_factory', '@prooph_event_store.message_converter', '@prooph_event_store.payload_serializer', '%prooph_event_store.stream_table_map%']

  prooph_event_sourcing.aggregate_translator:
    class: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator

  prooph_event_store_bus_bridge.transaction_manager:
    class: Prooph\EventStoreBusBridge\TransactionManager
    tags:
      - { name: 'prooph_event_store.herd_store.plugin' }

  prooph_event_store_bus_bridge.herd_event_publisher:
    class: Prooph\EventStoreBusBridge\EventPublisher
    arguments: ['@prooph_service_bus.herd_event_bus']
    tags:
      - { name: 'prooph_event_store.herd_store.plugin' }
