---

galaxy_info:
  author: "Jasper N. Brouwer, Ramon de la Fuente"
  description: Install Composer, the dependency manager for PHP
  company: Future500
  license: LGPL-3.0
  min_ansible_version: 1.4
  platforms:
  - name: Debian
    versions:
      - wheezy
      - jessie
      - stretch
      - buster
  categories:
    - web
    - system
